config/routes.rb
NcrmpSiteTracker::Application.routes.draw do
  root :to => 'locations#index'
  resources :locations
  match 'SEFCRI' => "locations#SEFCRI", via: [:get, :post]
  match 'Puerto_Rico' => "locations#Puerto_Rico", via: [:get, :post]
  match 'Florida_Keys' => "locations#Florida_Keys", via: [:get, :post]
  match 'DRTO' => "locations#DRTO", via: [:get, :post]
  match 'STX' => "locations#STX", via: [:get, :post]
  match 'STT_STJ' => "locations#STT_STJ", via: [:get, :post]

end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :latitude, :longitude, :site, :level, :need, :color, :is_reserved, :region_id, :fish_complete_date, :fish_complete_agency, :demo_complete_agency, :demo_complete_date, :depth

  scope :region,          lambda { |reg| where("region_id = ?", reg).load }
  scope :alternate,       lambda { where(level: 2).load }
  scope :primary,         lambda { where(level: 1).load }

  def getIconCode
    "#{self.need}#{self.color}"
  end
  
  def self.WhereAmI(region)
    case region
    when 1
      :Florida_Keys
    when 2
      :DRTO
    when 3
      :SEFCRI
    when 4
      :Puerto_Rico
    when 5
      :STX
    when 6
      :STT_STJ
    end
  end

  def DropDownMenu
    if self.need == 2
      [[1,"not started"], [2,"all complete"], [3,"fish complete"], [4,"demo complete"]]
    else 
      [[1,"not started"], [2,"all complete"]]
    end
  end

  def self.search(search)
    if !search.blank?
      find(:all, :conditions => ( search ? {:site => search.split( /, */ )} : []))
    else
      all
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations.to_json }
    end
  end

  def regionMap(reg)
    @locations = Location.region(reg).order(:site).search(params[:search])
    @primaryLocations = @locations.select { |location| location.level == 1 || location.level == 3 }
    @alternateLocations = @locations.select { |location| location.level == 2 }
    #@primaryLocations = @locations.where(level: [1,3])
    #@alternateLocations = @locations.where(level: 2)
    @primaryJson = []
    @alternateJson = []
    @primaryLocations.each do |loc|
      @primaryJson << { site: loc.site, latitude: loc.latitude, longitude: loc.longitude, level: loc.level, iconCode: loc.getIconCode, depth: loc.depth }
    end
    @alternateLocations.each do |loc|
      @alternateJson << { site: loc.site, latitude: loc.latitude, longitude: loc.longitude, level: loc.level, iconCode: loc.getIconCode, depth: loc.depth }
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @primaryJson.to_json }
      format.json { render json: @alternateJson.to_json }
    end
  end
  
  def Florida_Keys
    regionMap(1)
  end

  def DRTO
    regionMap(2)
  end

  def SEFCRI
    regionMap(3)
  end

  def Puerto_Rico
    regionMap(4)
  end

  def STX
    regionMap(5)
  end
  
  def STT_STJ
    regionMap(6)
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])
    
    @previousMap = Location.WhereAmI(@location.region_id)

    #binding.pry
    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @previousMap, notice: 'Location was successfully updated.' }
        format.json { respond_with_bip(@location) }
      else
        format.html { render action: "edit" }
        format.json { respond_with_bip(@location) }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when :notice then "info"
    when :error then "error"
    when :alert then "warning"
    end
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
  def google_maps_api_key
    "AIzaSyChS9Q56q7si6ehTu2o2X5d2fPKY2fHXjM"
  end

  def google_api_url
    "https://maps.googleapis.com/maps/api/js"
  end

  def google_api_access
    "#{google_api_url}?key=#{google_maps_api_key}&libraries=geometry&sensor=false"
  end

  def google_maps_api
    content_tag(:script,:type => "text/javascript",:src => google_api_access) do
    end
  end
end

app/views/layouts/_messages.html.erb
<% [:notice, :error, :alert].each do |level| %>
  <% unless flash[level].blank? %>
    <div class="alert alert-warning alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :p, flash[level] %>
    </div> 
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'navbar-brand' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NcrmpSiteTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= google_maps_api %>
  <%= csrf_meta_tags %>
</head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header class="">
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
          <div class="row">
            <div class="col-md-12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>

</html>

app/views/locations/DRTO.html.erb
<%= render 'regionMap' %>

app/views/locations/Florida_Keys.html.erb
<%= render 'regionMap' %>

app/views/locations/Puerto_Rico.html.erb
<%= render 'regionMap' %>

app/views/locations/SEFCRI.html.erb
<%= render 'regionMap' %>

app/views/locations/STT_STJ.html.erb
<%= render 'regionMap' %>

app/views/locations/STX.html.erb
<%= render 'regionMap' %>

app/views/locations/_form.html.erb
<%= form_for @location, :html => { :class => "form-horizontal"}  do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label class="col-sm-2 control-label">Site</label>
    <div class="col-sm-5">
      <input class="form-control" <%= f.text_field :site %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Latitude</label>
    <div class="col-sm-5">
      <input class="form-control"  <%= f.text_field :latitude %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Longitude</label>
    <div class="col-sm-5">
      <input class="form-control"  <%= f.text_field :longitude %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Level</label>
    <div class="col-sm-5">
      <select class="form-control"  <%= f.select :level, [["Primary",1], ["Alternate",2], ["No Habitat",3]] %>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Sample Types Needed</label>
      <div class="col-sm-5">
        <select class="form-control"  <%= f.select :need, [["Fish",1], ["Fish and Demo",2]] %>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 control-label">Completion Status</label>
        <div class="col-sm-5">
          <select class="form-control"  <%= f.select :color, [["Nothing Complete",1], ["All Complete",2],["Fish Only Complete",3], ["Demo Only Complete",4]] %>
          </div>
        </div>

        <div class="col-sm-offset-2">
          <div class="checkbox">
            <label> Is Reserved? </label> 
              <input type="checkbox"> <%= f.check_box :is_reserved %>
          </div>
        </div>

      
      <div class="form-group">
        <div class="col-sm-offset-6">
          <%= f.submit %>
        </div>
      </div>

<% end %>

app/views/locations/_legend.html.erb
<table class="legend" border="0">
  <tr>
    <th>Icon</th>
    <th>Status</th>
    <th>Total</th>
  </tr>
  <tr>
    <td><img src= <%= asset_path("mm_20_white.png") %> /></td>
    <td>Not Complete (Fish Sample only)</td>
    <td id="FishOnlyNotComplete">  </td>
  </tr>
   <tr>
     <td><img src= <%= asset_path("mm_20_green.png") %> /></td>
    <td>Complete (Fish Sample only)</td>
    <td id="FishOnlyComplete">  </td>
  </tr>
  <tr>
    <td><img src= <%= asset_path("WhiteTriangle.png") %> /></td>
    <td>Not Complete (Fish/LPI/Demo Sample)</td>
    <td id="AllThreeNotComplete">  </td>
  </tr>
  <tr>
    <td><img src= <%= asset_path("GreenTriangles.png") %> /></td>
    <td>All Complete (Fish/LPI/Demo Sample)</td>
    <td id="AllThreeComplete">  </td>
  </tr>
  <tr>
    <td><img src= <%= asset_path("YellowTriangle.png") %> /></td>
    <td>Fish Complete (Fish/LPI/Demo Sample)</td>
    <td id="AllThreeFishComplete">  </td>
  </tr>
  <tr>
    <td><img src= <%= asset_path("IndigoTriangle.png") %> /></td>
    <td>LPI/Demo Complete (Fish/LPI/Demo Sample)</td>
    <td id="AllThreeDemoComplete">  </td>
  </tr>
  <tr>
    <td><img src= <%= asset_path("Cross.png") %> /></td>
    <td>No Habitat Found</td>
    <td id="NoHabitat">  </td>
  </tr>
  <tr>
    <td><img src= <%= asset_path("mm_20_black.png") %> /></td>
    <td>Alternate</td>
  </tr>
</table>

app/views/locations/_regionMap.html.erb
<script>
  var primaryLocations = <%= raw @primaryJson.to_json %>
  var alternateLocations = <%= raw @alternateJson.to_json %>
</script>

<div class="row">
  <div class="col-md-10">
    <div id="floatingMap">
      <div id="map_canvas" style='width: 100%; height: 500px;'></div>
      <%= button_tag "Toggle Alternates", { :class => "btn", :id => "toggleMarkers" } %>
      <%= button_tag "Fish Sites Available", { id: "showFishSites", class: "btn", data: { toggle: "modal", target: "#fishModal" }} %>
      <%= button_tag "Demo Sites Available", { id: "showDemoSites", class: "btn", data: { toggle: "modal", target: "#demoModal" }} %>
      <%= button_tag "Toggle Habitat Map", { :class => "btn", :id => "toggleHabitatMap" } %>

<!-- Fish Modal -->
<div class="modal fade" id="fishModal" tabindex="-1" role="dialog" aria-labelledby="fishModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="fishModalLabel">Fish Sites Available</h4>
      </div>
      <div class="modal-body demo-modal">
        <table class="table modalTable" id="fishModalTable">
          <thead>
            <tr>
              <th>Site</th>
              <th>Latitude</th>
              <th>Longitude</th>
            </tr>
          </thead>
          <tbody>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div> 
<!-- Demo Modal -->
<div class="modal fade" id="demoModal" tabindex="-1" role="dialog" aria-labelledby="demoModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="demoModalLabel">Demo Sites Available</h4>
      </div>
      <div class="modal-body demo-modal">
        <table class="table modalTable" id="demoModalTable">
          <thead>
            <tr>
              <th>Site</th>
              <th>Latitude</th>
              <th>Longitude</th>
            </tr>
          </thead>
          <tbody>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div> 
    
    
    </div>
  </div>
  <div class="col-md-2 sideBar">
    <%= render 'legend' %>
  </div>
</div>

<br></br>
<%= button_tag "Refresh Map", { :class => "btn btn-primary btn-block", :id => "refreshMap" } %>
<br></br>
<div class='row infoTable'>
  <div class="col-md-12">
    <%= render 'siteTable' %>
  </div>
</div>

<div>
  <p></p>
</div>

app/views/locations/_siteTable.html.erb
<div class="fixed-table">
<div class="table-content">
  <table class ="dataTable" id="dataTable">

    <thead class="header">
    <tr>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Fish Complete Date</th>
      <th>Fish Complete Agency</th>
      <th>Demo Complete Date</th>
      <th>Demo Complete Agency</th>
      <th>Status</th>
      <th>is this Reserved</th>
    </tr>
    </thead>

    <% @locations.each do |location| %>
      <tr class="rowElement <%= location.is_reserved %>">
      <td class="name"><%= link_to location.site, edit_location_path(location) %></td>
      <td class="lat"><%= location.latitude %></td>
      <td class="lon"><%= location.longitude %></td>
      <td><%= best_in_place location, :fish_complete_date, :as => :date, :place_holder => "---------", :html_attrs => {:class => "datepicker"} %></td>
      <td><%= best_in_place location, :fish_complete_agency, :as => :input, :place_holder => "---------" %></td>
      <td><%= best_in_place location, :demo_complete_date, :as => :date, :place_holder => "---------", :html_attrs => {:class => "datepicker"} %></td>
      <td><%= best_in_place location, :demo_complete_agency, :as => :input, :place_holder => "---------" %></td>
      <td><%= best_in_place location, :color, :as => :select, :collection => location.DropDownMenu %></td>
      <td><%= best_in_place location, :is_reserved, as: :checkbox, collection: ["No", "Yes"], class:"isreserved" %></td>
    </tr>
    <% end %>
  </table>
</div>
</div>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

app/views/locations/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div id="floatingMap">
        <h3 class="head1">NCRMP Regions</h3>
        <div id="map_canvas2" style='width: 100%; height: 600px;'></div>
        <script>
          var map;
          var bounds = new google.maps.LatLngBounds();
          var mapOptions = {
            mapTypeId: 'roadmap'
          };

          // Display a map on the page
          map = new google.maps.Map(document.getElementById("map_canvas2"), mapOptions);

          // Multiple Markers
          var markers = [
          ['FLKEYS', 25.7573, -80.1235, '/ncrmp_site_tracker/Florida_Keys'],
          ['DRTO', 24.61954, -82.86407, '/ncrmp_site_tracker/DRTO'],
          ['SEFCRI', 27.184656, -80.042454, '/ncrmp_site_tracker/SEFCRI'],
          ['Puerto Rico', 18.51447, -66.50011, '/ncrmp_site_tracker/Puerto_Rico' ],
          ['St Thomas/John', 18.23378, -65.10017, '/ncrmp_site_tracker/STT_STJ' ],
          ['St Croix', 17.7823, -64.5955, '/ncrmp_site_tracker/STX' ]
          ];

          // Loop through our array of markers & place each one on the map  
          for( i = 0; i < markers.length; i++ ) {
            var position = new google.maps.LatLng(markers[i][1], markers[i][2]);
            bounds.extend(position);
            marker = new google.maps.Marker({
              position: position,
              map: map
            });

            marker.setTitle(markers[i][0]);
            attachMarkerUrl(marker,i);

            // Automatically center the map fitting all markers on the screen
            map.fitBounds(bounds);
          }
          function attachMarkerUrl(marker,num){
            google.maps.event.addListener(marker, 'click', function(){
              window.location = markers[num][3]
            });
          }
        </script>
      </div>
    </div>
  </div>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

app/views/locations/show.html.erb
<p>
  <b>Site:</b>
  <%= @location.site %>
</p>

<p>
  <b>Latitude:</b>
  <%= @location.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @location.longitude %>
</p>



<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>